# Generated by Django 3.2.5 on 2022-01-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_minik', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_lr', models.CharField(blank=True, max_length=50, null=True)),
                ('clean_post_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jd',
                'managed': False,
            },
        ),
    ]
